### ISSUE TITLE
Unable to import package when running `yarn dev` with v3.3.4

### ISSUE THREAD

**Issue by maddie** [imcvampire/vue-axios#108]
When running `yarn dev` with v3.3.4, error occurs:

```
yarn run v1.22.11
warning package.json: No license field
$ vite
 > src/main.ts:3:21: error: [plugin: vite:dep-scan] Failed to resolve entry for package "vue-axios". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-axios". The package may have incorrect main/module/exports specified in its package.json.
    3 │ import VueAxios from "vue-axios";
      ╵                      ~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
src/main.ts:3:21: error: [plugin: vite:dep-scan] Failed to resolve entry for package "vue-axios". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-axios". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (ui/node_modules/esbuild/lib/main.js:1451:15)
    at ui/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (ui/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (ui/node_modules/esbuild/lib/main.js:1129:7)
    at ui/node_modules/esbuild/lib/main.js:1238:14
    at ui/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (ui/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (ui/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Upon inspection, the `package.json` in `node_modules/vue-axios` defines `dist/vue-axios.esm.min.js` as main, whereas only `dist/vue-axios.common.min.js` is available in the package.

![image](https://user-images.githubusercontent.com/221872/132474117-9bc4f3f5-3518-48cb-aecf-9b6265f75790.png)

**Comment by imcvampire** [comment]
There is a problem introduced by the new build script. We are fixing it.

**Comment by imcvampire** [comment]
Please try the latest version - 3.3.6.
